[terminal.shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
padding = {}

[font]
size = 10.5

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[cursor]
style.shape = "Beam"

[colors.primary]
# hard contrast background = = '#1d2021'
# soft contrast background = = '#32302f'
background = '#1b1b1b' # gruvbox-material bg_dim
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

