#!/bin/bash

wallpapersDir="$HOME/.config/wallpapers/bg-cycle-wps"

if [ ! -d "$wallpapersDir" ]; then
    echo "Wallpapers directory does not exist"
    exit 1
fi

wallpapers=("$wallpapersDir"/*)
used_wallpapers=()

while true; do
    # If all wallpapers have been used, reset
    if [ ${#wallpapers[@]} -eq 0 ]; then
        wallpapers=("${used_wallpapers[@]}")
        used_wallpapers=()
    fi

    wallpaperIndex=$(( RANDOM % ${#wallpapers[@]} ))
    selectedWallpaper="${wallpapers[$wallpaperIndex]}"

    feh --bg-scale "$selectedWallpaper"

    # Move the used wallpaper to the used_wallpapers array
    used_wallpapers+=("$selectedWallpaper")
    unset 'wallpapers[wallpaperIndex]'
    
    # Rebuild wallpapers array with non-empty elements
    wallpapers=("${wallpapers[@]}")

    # Sleep for 20 minutes
    sleep 1200
done

