#!/bin/bash

schedule_shutdown() {
    local delay_minutes=6
    local delay_seconds=$((delay_minutes * 60))

    echo $(date +%H)
    if [ $(date +%H) -eq 23 ] && [ $(date +%M) -ge 15 ]; then
        delay_minutes=0
        delay_seconds=0
    fi

    shutdown -h +$delay_minutes --no-wall

    (
        sleep $((delay_seconds - 30))
        notify-send "System Shutdown" "YOOOOOOOOO"
    ) &
}

journalctl --user -o cat -f | while read -r line; do
    if [[ "$line" == *"System shutdown has been cancelled"* ]]; then
        notify-send "Shutdown Cancelled" "System shutdown has been cancelled."
        schedule_shutdown
    fi
done
